# Generated by Django 4.2 on 2024-12-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TickoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Client',
        ),
    ]
