# Generated by Django 4.2 on 2024-12-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickoApp', '0002_rename_member_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
