# Generated by Django 4.2 on 2024-12-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TickoApp', '0003_admini'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admini',
            new_name='Admin',
        ),
    ]
