# Generated by Django 4.2 on 2024-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickoApp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('depart', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('bus', models.CharField(max_length=20)),
                ('seatno', models.CharField(max_length=20)),
            ],
        ),
    ]
